### ISSUE TITLE
Some terms are missing definitions

### ISSUE THREAD

**Issue by chayev** [jargonary/jargonary.org#5]
There are a few terms that are missing definitions. When that is the case the page for term has a blank white box where the definition should be:

Terms that are missing definitions and acronyms: 
- Cohort
- Profit
- Revenue
- Sales Qualified Leads
- Service Level Agreement

Terms that have acronyms but no definitions:
- Annual Contract Value
- Average Revenue Per User
- Cost of Goods Sold

**Comment by FelicianoTech** [comment]
Thanks. Do you have any interest in providing/updating any of these?
